// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdpptubeifzxxxonjsbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkcHB0dWJlaWZ6eHh4b25qc2JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTU2MjksImV4cCI6MjA2MzkzMTYyOX0.Dr7je4uK_u--R1ssffiD_9cBUK0Er3BYLBmomLkESng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);